/*
 * Copyright (c) 2021 Paras Khanchandani
 * All rights reserved.
 */

export const UPDATE_TIME = 'UPDATE_TIME';
export const UPDATE_WEATHER = 'UPDATE_WEATHER';
export const UPDATE_MEDIA = 'UPDATE_MEDIA';
export const UPDATE_APPS = 'UPDATE_APPS';
export const ADD_APPS = 'ADD_APPS';
export const REPLACE_APPS = 'REPLACE_APPS';
export const REMOVE_APPS = 'REMOVE_APPS';
export const ADD_VALUE = 'ADD_VALUE';
export const REMOVE_VALUE = 'REMOVE_VALUE';
export const UPDATE_COMMS = 'UPDATE_COMMS';
export const UPDATE_RESOURCES = 'UPDATE_RESOURCES';
export const OPEN_START_MENU = 'OPEN_START_MENU';
export const SEARCHBAR_ACTIVE = 'SEARCHBAR_ACTIVE';
export const SEARCHQUERY = 'SEARCHQUERY';
export const SHOWMENU = 'SHOWMENU';
export const ADD_APPS_MENU = 'ADD_APPS_MENU';
export const REPLACE_APPS_MENU = 'REPLACE_APPS_MENU';
export const REMOVE_FOLDER_MENU = 'REMOVE_FOLDER_MENU';
export const REMOVE_APP_FROM_FOLDER_MENU = 'REMOVE_APP_FROM_FOLDER_MENU';
export const REMOVE_APP_FROM_PAGE_MENU = 'REMOVE_APP_FROM_PAGE_MENU';
export const OPEN_CC = 'OPEN_CC';
export const UPDATE_SYSTEM = 'UPDATE_SYSTEM';
export const INVOKE_REPLACE_APPS = 'INVOKE_REPLACE_APPS';
export const SETTINGS_OPEN = 'SETTINGS_OPEN';
export const WEATHER_OPEN = 'WEATHER_OPEN';
export const EXPLORER_OPEN = 'EXPLORER_OPEN';
export const CALENDAR_OPEN = 'CALENDAR_OPEN';
export const MEDIA_OPEN = 'MEDIA_OPEN';
export const REMINDERS_OPEN = 'REMINDERS_OPEN';
export const ADD_DOCUMENT_FOLDER = 'ADD_DOCUMENT_FOLDER';
export const ADD_PHOTO_FOLDER = 'ADD_PHOTO_FOLDER';
export const ADD_MUSIC_FOLDER = 'ADD_MUSIC_FOLDER';
export const ADD_VIDEO_FOLDER = 'ADD_VIDEO_FOLDER';
export const REMOVE_DOCUMENT_FOLDER = 'REMOVE_DOCUMENT_FOLDER';
export const REMOVE_PHOTO_FOLDER = 'REMOVE_PHOTO_FOLDER';
export const REMOVE_MUSIC_FOLDER = 'REMOVE_MUSIC_FOLDER';
export const REMOVE_VIDEO_FOLDER = 'REMOVE_VIDEO_FOLDER';
export const OPEN_FOLDER = 'OPEN_FOLDER';
export const CLOSE_FOLDER = 'CLOSE_FOLDER';
export const ADD_APP_TO_FOLDER = 'ADD_APP_TO_FOLDER';
export const REMOVE_APP_FROM_FOLDER = 'REMOVE_APP_FROM_FOLDER';
export const ADD_APP_TO_PAGE = 'ADD_APP_TO_PAGE';
export const REMOVE_APP_FROM_PAGE = 'REMOVE_APP_FROM_PAGE';
export const OPEN_COLOR_PICKER = 'OPEN_COLOR_PICKER';
export const CLOSE_COLOR_PICKER = 'CLOSE_COLOR_PICKER';
